# Data Cleaning

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [70]:
df=pd.read_excel('Zomato_Data.xlsx')

In [71]:
df.describe()

       Delivery_Time_Min       Rating  Discount_Percent  Distance_km
count        4871.000000  3094.000000       3314.000000  4894.000000
mean           52.355984     2.997738         12.481895    13.169044
std            21.974629     1.406302          5.659399     6.963143
min            15.000000     1.000000          5.000000     1.000000
25%            33.000000     2.000000          5.000000     7.200000
50%            52.000000     3.000000         10.000000    13.100000
75%            71.000000     4.000000         20.000000    19.300000
max            90.000000     5.000000         20.000000    25.000000

In [72]:
df.shape

(5000, 14)

In [73]:
df.head()

,Order_ID,Customer_Name,City,Restaurant_Name,Cuisine,Order_Amount,Delivery_Time_Min,Rating,Payment_Method,Delivery_Status,Discount_Percent,Order_Date,Customer_Age,Distance_km
0,ZM100000,Nitara Andra,Chandigarh,Bath-Kapur Restaurant,South Indian,390.86,84.0,2.0,Wallet,Delivered,5.0,2025-06-21,23,13.1
1,ZM100001,Trisha Bhargava,delhi,"Ramaswamy, Dhar and Sani Restaurant",Desserts,1534.77,15.0,3.0,Wallet,Cancelled,15.0,2026-05-01,27,19.3
2,ZM100002,Ranbir Dhar,Hyderabad,Mander-Halder Restaurant,Fast Food,1864.87,63.0,2.0,Card,Pending,NaN,2026-03-23,41,17.9
3,ZM100003,Aarush Kunda,Mumbai,Kar Inc Restaurant,South Indian,1043.3,61.0,3.0,Card,Cancelled,10.0,2026-04-21,NaN,23.5
4,ZM100004,Trisha Gade,delhi,Kant Inc Restaurant,South Indian,1041.72,86.0,4.0,Card,Delivered,10.0,2025-06-17,20,10.6

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           4956 non-null   object
 1   Customer_Name      5000 non-null   object
 2   City               4510 non-null   object
 3   Restaurant_Name    5000 non-null   object
 4   Cuisine            5000 non-null   object
 5   Order_Amount       5000 non-null   object
 6   Delivery_Time_Min  4871 non-null   float64
 7   Rating             3094 non-null   float64
 8   Payment_Method     5000 non-null   object
 9   Delivery_Status    5000 non-null   object
 10  Discount_Percent   3314 non-null   float64
 11  Order_Date         5000 non-null   object
 12  Customer_Age       4764 non-null   object
 13  Distance_km        4894 non-null   float64
dtypes: float64(4), object(10)
memory usage: 547.0+ KB

In [75]:
df['Order_Amount']

0        390.86
1       1534.77
2       1864.87
3        1043.3
4       1041.72
         ...
4995    2332.81
4996    1671.24
4997    2107.09
4998     946.28
4999    2117.07
Name: Order_Amount, Length: 5000, dtype: object

In [76]:
df['Order_Amount'] = pd.to_numeric(df['Order_Amount'], errors='coerce')

In [77]:
df['Order_Amount']=df['Order_Amount'].fillna(df['Order_Amount'].mean())

In [78]:
df.isnull().sum()

Order_ID               44
Customer_Name           0
City                  490
Restaurant_Name         0
Cuisine                 0
Order_Amount            0
Delivery_Time_Min     129
Rating               1906
Payment_Method          0
Delivery_Status         0
Discount_Percent     1686
Order_Date              0
Customer_Age          236
Distance_km           106
dtype: int64

In [79]:
df['Order_Date']=pd.to_datetime(df['Order_Date'])

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           4956 non-null   object
 1   Customer_Name      5000 non-null   object
 2   City               4510 non-null   object
 3   Restaurant_Name    5000 non-null   object
 4   Cuisine            5000 non-null   object
 5   Order_Amount       5000 non-null   float64
 6   Delivery_Time_Min  4871 non-null   float64
 7   Rating             3094 non-null   float64
 8   Payment_Method     5000 non-null   object
 9   Delivery_Status    5000 non-null   object
 10  Discount_Percent   3314 non-null   float64
 11  Order_Date         5000 non-null   datetime64[ns]
 12  Customer_Age       4764 non-null   object
 13  Distance_km        4894 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(8)
memory usage: 547.0+ KB

In [81]:
df['Customer_Age']=pd.to_numeric(df['Customer_Age'],errors='coerce')

In [82]:
df['Customer_Age']=df['Customer_Age'].fillna(df['Customer_Age'].median())

In [83]:
df.isnull().sum()

Order_ID               44
Customer_Name           0
City                  490
Restaurant_Name         0
Cuisine                 0
Order_Amount            0
Delivery_Time_Min     129
Rating               1906
Payment_Method          0
Delivery_Status         0
Discount_Percent     1686
Order_Date              0
Customer_Age            0
Distance_km           106
dtype: int64

In [84]:
df.shape

(5000, 14)

In [85]:
df = df.dropna(subset=['Order_ID'])

In [86]:
df['City']=df['City'].fillna('NA')

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4956 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           4956 non-null   object
 1   Customer_Name      4956 non-null   object
 2   City               4956 non-null   object
 3   Restaurant_Name    4956 non-null   object
 4   Cuisine            4956 non-null   object
 5   Order_Amount       4956 non-null   float64
 6   Delivery_Time_Min  4827 non-null   float64
 7   Rating             3066 non-null   float64
 8   Payment_Method     4956 non-null   object
 9   Delivery_Status    4956 non-null   object
 10  Discount_Percent   3281 non-null   float64
 11  Order_Date         4956 non-null   datetime64[ns]
 12  Customer_Age       4956 non-null   float64
 13  Distance_km        4852 non-null   float64
dtypes: datetime64[ns](1), float64(6), object(7)
memory usage: 580.8+ KB

In [88]:
df.isnull().sum()

Order_ID                0
Customer_Name           0
City                    0
Restaurant_Name         0
Cuisine                 0
Order_Amount            0
Delivery_Time_Min     129
Rating               1890
Payment_Method          0
Delivery_Status         0
Discount_Percent     1675
Order_Date              0
Customer_Age            0
Distance_km           104
dtype: int64

In [89]:
df['Delivery_Time_Min']=df['Delivery_Time_Min'].fillna(df['Delivery_Time_Min'].mean())

In [90]:
df['Distance_km']=df['Distance_km'].fillna(df['Delivery_Time_Min'].mean())

In [91]:
df['Discount_Percent'] = df['Discount_Percent'].fillna(0)

In [92]:
df['Rating'] = df['Rating'].fillna(df['Rating'].median())

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4956 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           4956 non-null   object
 1   Customer_Name      4956 non-null   object
 2   City               4956 non-null   object
 3   Restaurant_Name    4956 non-null   object
 4   Cuisine            4956 non-null   object
 5   Order_Amount       4956 non-null   float64
 6   Delivery_Time_Min  4956 non-null   float64
 7   Rating             4956 non-null   float64
 8   Payment_Method     4956 non-null   object
 9   Delivery_Status    4956 non-null   object
 10  Discount_Percent   4956 non-null   float64
 11  Order_Date         4956 non-null   datetime64[ns]
 12  Customer_Age       4956 non-null   float64
 13  Distance_km        4956 non-null   float64
dtypes: datetime64[ns](1), float64(6), object(7)
memory usage: 580.8+ KB

In [94]:
df.isnull().sum()

Order_ID             0
Customer_Name        0
City                 0
Restaurant_Name      0
Cuisine              0
Order_Amount         0
Delivery_Time_Min    0
Rating               0
Payment_Method       0
Delivery_Status      0
Discount_Percent     0
Order_Date           0
Customer_Age         0
Distance_km          0
dtype: int64

In [95]:
df.duplicated().sum()

np.int64(0)

In [96]:
df.describe()

,Order_Amount,Delivery_Time_Min,Rating,Discount_Percent,Order_Date,Customer_Age,Distance_km
count,4956.000000,4956.000000,4956.000000,4956.000000,4956,4956.000000,4956.000000
mean,1316.419522,52.386576,2.999193,8.267756,2025-11-12 14:25:16.707021568,38.545803,13.984383
min,150.280000,15.000000,1.000000,0.000000,2025-05-15 00:00:00,18.000000,1.000000
25%,764.020000,34.000000,3.000000,0.000000,2025-08-14 18:00:00,29.000000,7.300000
50%,1316.109302,52.386576,3.000000,5.000000,2025-11-11 00:00:00,38.500000,13.400000
75%,1881.850000,71.000000,3.000000,15.000000,2026-02-12 00:00:00,48.000000,19.700000
max,2499.740000,90.000000,5.000000,20.000000,2026-05-14 00:00:00,59.000000,52.386576
std,659.498379,21.668890,1.107173,7.489026,NaN,11.692077,8.889673

In [97]:
df['Customer_Name']=df['Customer_Name'].str.strip().str.title()

In [98]:
(df['Customer_Name'] == '').sum()

np.int64(139)

In [99]:
df['Customer_Name'] = df['Customer_Name'].replace('', np.nan)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4956 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           4956 non-null   object
 1   Customer_Name      4817 non-null   object
 2   City               4956 non-null   object
 3   Restaurant_Name    4956 non-null   object
 4   Cuisine            4956 non-null   object
 5   Order_Amount       4956 non-null   float64
 6   Delivery_Time_Min  4956 non-null   float64
 7   Rating             4956 non-null   float64
 8   Payment_Method     4956 non-null   object
 9   Delivery_Status    4956 non-null   object
 10  Discount_Percent   4956 non-null   float64
 11  Order_Date         4956 non-null   datetime64[ns]
 12  Customer_Age       4956 non-null   float64
 13  Distance_km        4956 non-null   float64
dtypes: datetime64[ns](1), float64(6), object(7)
memory usage: 580.8+ KB

In [101]:
df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')

In [102]:
df['City']=df['City'].str.strip().str.title()

In [103]:
df['Order_ID'].str.strip()

0       ZM100000
1       ZM100001
2       ZM100002
3       ZM100003
4       ZM100004
          ...
4995    ZM104995
4996    ZM104996
4997    ZM104997
4998    ZM104998
4999    ZM104999
Name: Order_ID, Length: 4956, dtype: object

In [104]:
df[df['Order_ID'] == '']

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Restaurant_Name, Cuisine, Order_Amount, Delivery_Time_Min, Rating, Payment_Method, Delivery_Status, Discount_Percent, Order_Date, Customer_Age, Distance_km]
Index: []

In [105]:
df['Restaurant_Name']=df['Restaurant_Name'].str.strip().str.title()

In [106]:
df['Cuisine']=df['Cuisine'].str.strip().str.title()

In [107]:
df['Payment_Method']=df['Payment_Method'].str.strip().str.title()

In [108]:
df['Delivery_Status']=df['Delivery_Status'].str.strip().str.title()

Performed comprehensive data cleaning by handling missing values, converting data types, standardizing categorical fields, removing hidden blank values, validating data quality, and engineering date-based features for analysis.

In [110]:
df.to_csv('Zomato_Cleaned_Data.csv', index=False)